version: '3.8'
services:
  backend-weather-challenge-test-runner:
    build:
      context: ./
      dockerfile: ./Dockerfile

    command: make test.watch

    volumes:
      - ./Makefile:/opt/app/Makefile
      - ./package.json:/opt/app/package.json
      - ./pnpm-lock.yaml:/opt/app/pnpm-lock.yaml
      - ./src:/opt/app/src
      - ./test:/opt/app/test